# Generated by Django 5.1.4 on 2025-01-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutormarketplace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutor",
            name="phone",
        ),
        migrations.AlterField(
            model_name="tutor",
            name="rating",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                max_length=10,
            ),
        ),
    ]
