# Generated by Django 5.1.4 on 2025-02-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutormarketplace", "0003_alter_tutor_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tutor",
        ),
    ]
