# Generated by Django 5.1.4 on 2024-12-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_alter_user_level"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tutor",
        ),
    ]
